In [13]:
import pandas as pd
import re
!pip install textblob
from collections import Counter

Requirement already satisfied: textblob in c:\python312\lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\python312\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\python312\lib\site-packages (from nltk>=3.9->textblob) (8.1.8)
Requirement already satisfied: joblib in c:\python312\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\python312\lib\site-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in c:\python312\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\python312\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# Load the dataset
file_path = "DisneylandReviews.csv"  # Update with the correct path if needed
df = pd.read_csv(file_path, encoding="latin1")

# Remove rows where 'Year_Month' is 'missing'
df = df[df['Year_Month'] != 'missing']

# Convert 'Year_Month' to datetime format
df['Year_Month'] = pd.to_datetime(df['Year_Month'], format='%Y-%m')

# Remove duplicate rows
df = df.drop_duplicates()

# Clean 'Review_Text' (lowercase and remove special characters)
df['Review_Text'] = df['Review_Text'].str.lower().str.replace(r'[^a-z0-9\s]', '', regex=True)

# Display dataset info and sample
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 40031 entries, 0 to 42117
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Review_ID          40031 non-null  int64
 1   Rating             40031 non-null  int64
 2   Year_Month         40031 non-null  datetime64[ns]
 3   Reviewer_Location  40031 non-null  object
 4   Review_Text        40031 non-null  object
 5   Branch             40031 non-null  object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 2.1+ MB
None
   Review_ID  Rating Year_Month     Reviewer_Location  \
0  670772142       4 2019-04-01             Australia
1  670682799       4 2019-05-01           Philippines
2  670623270       4 2019-04-01  United Arab Emirates
3  670607911       4 2019-04-01             Australia
4  670607296       4 2019-04-01        United Kingdom

                                         Review_Text               Branch
0  if youve ever been to disneyland anywhere youl...  Disneyland_HongKong
1  its been a while since d last time we visit hk...  Disneyland_HongKong
2  thanks god it wasn   t too hot or too humid wh...  Disneyland_HongKong
3  hk disneyland is a great compact park unfortun...  Disneyland_HongKong
4  the location is not in the city took around 1 ...  Disneyland_HongKong

In [4]:
# Convert review text to lowercase for uniform processing
df['Review_Text'] = df['Review_Text'].astype(str).str.lower()

# Define keyword-based classification
def visitor_type(review):
    if re.search(r"\bfirst time\b", review):
        return "First-Time Visitor"
    elif re.search(r"\b(again|second visit|returning|back)\b", review):
        return "Returning Visitor"
    else:
        return "Unknown"

# Apply function to create new column
df['Visitor_Type'] = df['Review_Text'].apply(visitor_type)

# Export the processed data
export_path = "C:\\Users\\Shreyas MN\\Desktop\\Uh Academics\\Information Visualization\\PROJECT 2.0\\DisneylandReviews_Processed.csv"  # Modify for local system
df.to_csv(export_path, index=False)

print("Processing Complete! Cleaned data saved as:", export_path)

Processing Complete! Cleaned data saved as: C:\Users\Shreyas MN\Desktop\Uh Academics\Information Visualization\PROJECT 2.0\DisneylandReviews_Processed.csv

In [7]:
df

,Review_ID,Rating,Year_Month,Reviewer_Location,Review_Text,Branch,Visitor_Type
0,670772142,4,2019-04-01,Australia,if youve ever been to disneyland anywhere youl...,Disneyland_HongKong,Unknown
1,670682799,4,2019-05-01,Philippines,its been a while since d last time we visit hk...,Disneyland_HongKong,Unknown
2,670623270,4,2019-04-01,United Arab Emirates,thanks god it wasn t too hot or too humid wh...,Disneyland_HongKong,Unknown
3,670607911,4,2019-04-01,Australia,hk disneyland is a great compact park unfortun...,Disneyland_HongKong,Unknown
4,670607296,4,2019-04-01,United Kingdom,the location is not in the city took around 1 ...,Disneyland_HongKong,Unknown
...,...,...,...,...,...,...,...
42113,92198076,4,2011-01-01,United Kingdom,although our pick up was prompt the taxi drive...,Disneyland_Paris,Returning Visitor
42114,92061774,4,2011-01-01,Germany,just returned from a 4 days family trip to dis...,Disneyland_Paris,Returning Visitor
42115,91995748,1,2010-12-01,United Kingdom,we spent the 20 dec 2010 in the disney park an...,Disneyland_Paris,Returning Visitor
42116,91984642,2,2010-12-01,United Kingdom,well i was really looking forward to this trip...,Disneyland_Paris,Returning Visitor
42117,91827418,5,2010-09-01,United Kingdom,if staying at a disney hotel make good use of ...,Disneyland_Paris,Unknown

In [5]:
# Count the number of each visitor type
visitor_counts = df['Visitor_Type'].value_counts()

# Display the counts
print("Visitor Type Counts:")
print(visitor_counts)

Visitor Type Counts:
Visitor_Type
Unknown               28525
Returning Visitor      9770
First-Time Visitor     1736
Name: count, dtype: int64

In [14]:
import pandas as pd
import numpy as np
import re
#import TextBlob

# Load Dataset
file_path = "DisneylandReviews.csv"  # Update with the correct path if needed
df = pd.read_csv(file_path, encoding="latin1")

#1. Date & Time Features
df['Year_Month'] = pd.to_datetime(df['Year_Month'], format='%Y-%m', errors='coerce')
df['year'] = df['Year_Month'].dt.year
df['month'] = df['Year_Month'].dt.month
df['month_name'] = df['Year_Month'].dt.month_name()
df['day_of_week'] = np.random.choice(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], size=len(df))

#2. Review Text Features
df['review_length'] = df['Review_Text'].apply(lambda x: len(str(x)))  # Length of review
df['review_word_count'] = df['Review_Text'].apply(lambda x: len(str(x).split()))  # Number of words
df['review_sentence_count'] = df['Review_Text'].apply(lambda x: len(str(x).split('.')))  # Number of sentences
df['word_density'] = df['review_word_count'] / df['review_length']  # Words per character
df['uppercase_count'] = df['Review_Text'].apply(lambda x: sum(1 for c in str(x) if c.isupper()))  # Uppercase letters
df['digit_count'] = df['Review_Text'].apply(lambda x: sum(c.isdigit() for c in str(x)))  # Number of digits
df['punctuation_count'] = df['Review_Text'].apply(lambda x: sum(1 for c in str(x) if c in "!?,."))  # Punctuation count

# 3. Sentiment & Emotion Analysis
def get_sentiment(text):
    try:
        sentiment = TextBlob(str(text)).sentiment
        return sentiment.polarity, sentiment.subjectivity
    except:
        return 0, 0

df[['sentiment_polarity', 'sentiment_subjectivity']] = df['Review_Text'].apply(lambda x: pd.Series(get_sentiment(x)))

df['review_has_exclamation'] = df['Review_Text'].apply(lambda x: 1 if '!' in str(x) else 0)
df['review_has_question'] = df['Review_Text'].apply(lambda x: 1 if '?' in str(x) else 0)
df['review_has_numbers'] = df['Review_Text'].apply(lambda x: 1 if any(c.isdigit() for c in str(x)) else 0)

#4. User & Location Features
df['location_encoded'] = df['Reviewer_Location'].astype('category').cat.codes  # Convert locations into numbers
df['location_length'] = df['Reviewer_Location'].apply(lambda x: len(str(x)))  # Length of location name

#5. Branch & Disneyland-Specific Features
df['branch_encoded'] = df['Branch'].astype('category').cat.codes  # Convert branches into numbers

#6. Rating & Engagement Features
df['rating_category'] = df['Rating'].apply(lambda x: 'Low' if x <= 2 else ('Medium' if x <= 4 else 'High'))
df['is_high_rating'] = df['Rating'].apply(lambda x: 1 if x == 5 else 0)  # 1 if the rating is 5, else 0

#7. Most Common Words in Reviews
def most_common_words(text, n=5):
    words = re.findall(r'\b\w+\b', str(text).lower())  # Extract words
    return [word for word, count in Counter(words).most_common(n)]

df['top_5_words'] = df['Review_Text'].apply(lambda x: most_common_words(x, 5))

#8. Interaction-Based Features
df['review_has_adjectives'] = df['Review_Text'].apply(lambda x: any(word in str(x).lower() for word in ['amazing', 'great', 'awesome', 'bad', 'terrible']))
df['review_has_comparison_words'] = df['Review_Text'].apply(lambda x: any(word in str(x).lower() for word in ['better', 'worse', 'best', 'worst', 'than']))

# Display extracted features
print(df.head())

   Review_ID  Rating Year_Month     Reviewer_Location  \
0  670772142       4 2019-04-01             Australia
1  670682799       4 2019-05-01           Philippines
2  670623270       4 2019-04-01  United Arab Emirates
3  670607911       4 2019-04-01             Australia
4  670607296       4 2019-04-01        United Kingdom

                                         Review_Text               Branch  \
0  If you've ever been to Disneyland anywhere you...  Disneyland_HongKong
1  Its been a while since d last time we visit HK...  Disneyland_HongKong
2  Thanks God it wasn   t too hot or too humid wh...  Disneyland_HongKong
3  HK Disneyland is a great compact park. Unfortu...  Disneyland_HongKong
4  the location is not in the city, took around 1...  Disneyland_HongKong

     year  month month_name day_of_week  ...  review_has_question  \
0  2019.0    4.0      April      Sunday  ...                    0
1  2019.0    5.0        May      Monday  ...                    0
2  2019.0    4.0      April      Friday  ...                    0
3  2019.0    4.0      April      Monday  ...                    0
4  2019.0    4.0      April      Friday  ...                    0

   review_has_numbers  location_encoded  location_length  branch_encoded  \
0                   0                 8                9               1
1                   1               114               11               1
2                   1               151               20               1
3                   0                 8                9               1
4                   1               152               14               1

   rating_category  is_high_rating                      top_5_words  \
0           Medium               0  [the, you, disneyland, very, a]
1           Medium               0             [n, d, have, to, hk]
2           Medium               0           [i, was, the, and, it]
3           Medium               0     [is, a, the, disneyland, of]
4           Medium               0     [the, is, in, location, not]

   review_has_adjectives  review_has_comparison_words
0                  False                        False
1                   True                         True
2                   True                         True
3                   True                        False
4                  False                        False

[5 rows x 30 columns]

In [16]:
# Count the number of features
num_features = len(df.columns)

# Print all feature names with count
print(f"Total Number of Extracted Features: {num_features}")
print("Extracted Features:")
for col in df.columns:
    print(col)

Total Number of Extracted Features: 30
Extracted Features:
Review_ID
Rating
Year_Month
Reviewer_Location
Review_Text
Branch
year
month
month_name
day_of_week
review_length
review_word_count
review_sentence_count
word_density
uppercase_count
digit_count
punctuation_count
sentiment_polarity
sentiment_subjectivity
review_has_exclamation
review_has_question
review_has_numbers
location_encoded
location_length
branch_encoded
rating_category
is_high_rating
top_5_words
review_has_adjectives
review_has_comparison_words

In [17]:
# Export the processed data
export_path = "C:\\Users\\Shreyas MN\\Desktop\\Uh Academics\\Information Visualization\\PROJECT 2.0\\DisneylandReviews_Extracted.csv"  # Modify for local system
df.to_csv(export_path, index=False)

#print("Processing Complete! Cleaned data saved as:", export_path)

In [20]:

import re

def preprocess_disneyland_reviews(file_path):
    # Load dataset
    df = pd.read_csv(file_path)
    
    # 1. Handling Missing Values
    df['Year_Month'].fillna('Unknown', inplace=True)
    df['year'].fillna(df['year'].median(), inplace=True)
    df['month'].fillna(df['month'].median(), inplace=True)
    df['month_name'].fillna('Unknown', inplace=True)
    
    # Convert year and month to integer
    df['year'] = df['year'].astype(int)
    df['month'] = df['month'].astype(int)
    
    # 2. Cleaning Review Text
    def clean_text(text):
        text = str(text).lower()  # Convert to lowercase
        text = re.sub(r'[^a-z0-9.,!?\s]', '', text)  # Remove special characters
        text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
        return text
    
    df['Review_Text'] = df['Review_Text'].apply(clean_text)
    
    # 3. Handling Outliers
    for col in ['review_length', 'review_word_count', 'review_sentence_count']:
        upper_limit = df[col].quantile(0.99)
        lower_limit = df[col].quantile(0.01)
        df[col] = np.clip(df[col], lower_limit, upper_limit)
    
    # 4. Correct Sentiment Scores if needed
    df['sentiment_polarity'] = df['sentiment_polarity'].astype(float)
    df['sentiment_subjectivity'] = df['sentiment_subjectivity'].astype(float)
    
    # Save the cleaned dataset
    cleaned_file_path = file_path.replace('.csv', '_cleaned.csv')
    df.to_csv(cleaned_file_path, index=False)
    
    return cleaned_file_path

# Update the file path with your local directory
file_path = r"C:\Users\Shreyas MN\Desktop\Uh Academics\Information Visualization\PROJECT 2.0\DisneylandReviews_Extracted.csv"

# Run the preprocessing function
cleaned_file = preprocess_disneyland_reviews(file_path)

print(f'Cleaned data saved at: {cleaned_file}')

C:\Users\Shreyas MN\AppData\Local\Temp\ipykernel_59524\975484752.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Year_Month'].fillna('Unknown', inplace=True)
C:\Users\Shreyas MN\AppData\Local\Temp\ipykernel_59524\975484752.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['year'].fillna(df['year'].median(), inplace=True)
C:\Users\Shreyas MN\AppData\Local\Temp\ipykernel_59524\975484752.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['month'].fillna(df['month'].median(), inplace=True)
C:\Users\Shreyas MN\AppData\Local\Temp\ipykernel_59524\975484752.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['month_name'].fillna('Unknown', inplace=True)

Cleaned data saved at: C:\Users\Shreyas MN\Desktop\Uh Academics\Information Visualization\PROJECT 2.0\DisneylandReviews_Extracted_cleaned.csv